[package]
name = "rust_cmake_cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build_dependencies]
bindgen = "0.60.1"
cmake = "0.1.49"

[dependencies]
libc = "0.2.140"
